### ISSUE TITLE
grid overriding gutters

### ISSUE THREAD

**Issue by ArekRado** [7ninjas/scss-mixins#101]
```scss
  @include container;
  @include media-breakpoint-down(sm) {
    @include container($gutter: false);
  }
```

it's not possible to override first container by container without gutters. I have to use breakpoints:

```scss
  @include media-breakpoint-up(sm) {
    @include container;
  }
  @include media-breakpoint-down(sm) {
    @include container($gutter: false);
  }
```

## how to fix it:
we need to update gutter mixin by adding `else if`

```scss
@mixin gutter($gutter: $grid-gutter-widths) {
  @if $gutter {
    @each $breakpoint-query, $gutter-width in $gutter {
      @include media-breakpoint-variant($breakpoint-query) {
        padding-left: ($gutter-width / 2);
        padding-right: ($gutter-width / 2);
      }
    }
  }
} else { 
  padding-left: 0;
  padding-right: 0;
}
``` 

It's breaking change so should be available on 2.0 version
